all: exceptionExecutionPolicy

clean:
	rm -rf execeptionExecutionPolicy 

execeptionExecutionPolicy:
	g++ -std=c++17 -o exceptionExecutionPolicy exceptionExecutionPolicy.cpp -Wall -ltbb -DPARALLEL -g


