#pragma once
#include "overload_invoke.h"

#define MAKE_INDEX_SEQUENCE_0() 0
#define MAKE_INDEX_SEQUENCE_1() MAKE_INDEX_SEQUENCE_0(), 1
#define MAKE_INDEX_SEQUENCE_2() MAKE_INDEX_SEQUENCE_1(), 2
#define MAKE_INDEX_SEQUENCE_3() MAKE_INDEX_SEQUENCE_2(), 3
#define MAKE_INDEX_SEQUENCE_4() MAKE_INDEX_SEQUENCE_3(), 4
#define MAKE_INDEX_SEQUENCE_5() MAKE_INDEX_SEQUENCE_4()
#define MAKE_INDEX_SEQUENCE(index) \
	OVERLOAD_INVOKE(MAKE_INDEX_SEQUENCE,DEC(index))()